version: '3'

services:

  test:
    container_name: althingi_aggregator_test_container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - APPLICATION_ENVIRONMENT=development
    - CACHE_TYPE=none

    command: bash -c "/usr/src/vendor/bin/phpunit && /usr/src/vendor/bin/phpcs"
