version: '3'

services:

  test:
    container_name: althingi_aggregator_test_container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APPLICATION_ENVIRONMENT=development
      - PROVIDER_CACHE_TYPE=none
      - CONSUMER_CACHE_TYPE=none
    volumes:
      - ./auto/:/usr/src/auto
      - ./config/:/usr/src/config
      - ./module/:/usr/src/module
      - ./public/:/usr/src/public

    command: bash -c "composer development-enable && /usr/src/vendor/bin/phpunit && /usr/src/vendor/bin/phpcs"
