version: '3'

services:

  run:
    container_name: althingi_aggregator_run_container
    build:
      args:
        - ENV=development
      context: .
      dockerfile: Dockerfile
    environment:
      - CONSUMER_CACHE_TYPE=${ENV_CONSUMER_CACHE_TYPE:-none}
      - CONSUMER_CACHE_HOST=${ENV_CONSUMER_CACHE_HOST:-localhost}
      - CONSUMER_CACHE_PORT=${ENV_CONSUMER_CACHE_PORT:-6379}
      - CONSUMER_CACHE=${ENV_CONSUMER_CACHE:-false}

      - PROVIDER_CACHE_TYPE=${ENV_PROVIDER_CACHE_TYPE:-none}
      - PROVIDER_CACHE_HOST=${ENV_PROVIDER_CACHE_HOST:-localhost}
      - PROVIDER_CACHE_PORT=${ENV_PROVIDER_CACHE_PORT:-6379}
      - PROVIDER_CACHE=${ENV_PROVIDER_CACHE:-false}

      - AGGREGATOR_CONSUMER_SCHEMA=${ENV_AGGREGATOR_CONSUMER_SCHEMA:-http}
      - AGGREGATOR_CONSUMER_HOST=${ENV_AGGREGATOR_CONSUMER_HOST:-host.docker.internal}
      - AGGREGATOR_CONSUMER_PORT=${ENV_AGGREGATOR_CONSUMER_PORT:-8080}
    volumes:
      - ./bin/:/usr/src/bin
      - ./config/:/usr/src/config
      - ./src/:/usr/src/src
      - ./public/:/usr/src/public
      - ./vendor/:/usr/src/vendor
      - ./composer.json/:/usr/src/composer.json
      - ./composer.lock/:/usr/src/composer.lock

  test:
    container_name: althingi_aggregator_test_container
    build:
      args:
        - ENV=development
      context: .
      dockerfile: Dockerfile
    environment:
      - PROVIDER_CACHE_TYPE=none
      - CONSUMER_CACHE_TYPE=none
    working_dir: /usr/src
    volumes:
      - ./config/:/usr/src/config
      - ./src/:/usr/src/src
      - ./public/:/usr/src/public
      - ./tests/:/usr/src/tests
      - ./phpcs.xml/:/usr/src/phpcs.xml
      - ./phpunit.xml.dist/:/usr/src/phpunit.xml
    command: bash -c "./vendor/bin/phpunit && ./vendor/bin/phpcs --standard=./phpcs.xml ./src"
    # command: bash -c "./vendor/bin/phpunit --coverage-html ./tests/doc && ./vendor/bin/phpcs --standard=./phpcs.xml ./src"
